name: Publish to PyPI
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi-publish      # Match the Environment Name you set on PyPI
    permissions:
      contents: read               # Required for checkout
      id-token: write              # Enables OIDC to PyPI
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Build distributions
        run: |
          python -m pip install --upgrade build
          python -m build --sdist --wheel

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
