version: '3.8'

services:
  api:
    build: .
    ports:
      - "80:80"
    environment:
      - MODEL_PATH=./saved_models/isnet.pth
      - MAX_WORKERS=1
      - TIMEOUT=600
      - PORT=80
    volumes:
      - ./saved_models:/app/saved_models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3